// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARbeTF33nxmKnXsCvsf3r6Ditkr_eUV4k',
    appId: '1:173932211482:android:641e99251e5b9b292e50a3',
    messagingSenderId: '173932211482',
    projectId: 'flutter-moreyourbong',
    databaseURL: 'https://flutter-moreyourbong-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-moreyourbong.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvWZMYK-2-WM5gqy3GBjTyPKh5MC3Q7Js',
    appId: '1:173932211482:ios:5130126bda4ba77c2e50a3',
    messagingSenderId: '173932211482',
    projectId: 'flutter-moreyourbong',
    databaseURL: 'https://flutter-moreyourbong-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-moreyourbong.firebasestorage.app',
    iosBundleId: 'com.example.moreyourbong',
  );
}
