platform :ios, '15.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# (필요시) 정적 링크+모듈 헤더
use_frameworks! :linkage => :static
use_modular_headers!

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..','Flutter','Generated.xcconfig'), __FILE__)
  raise "#{generated_xcode_build_settings_path} must exist." unless File.exist?(generated_xcode_build_settings_path)
  File.foreach(generated_xcode_build_settings_path) do |line|
    m = line.match(/FLUTTER_ROOT\=(.*)/); return m[1].strip if m
  end
  raise "FLUTTER_ROOT not found"
end

require File.expand_path(File.join('packages','flutter_tools','bin','podhelper'), flutter_root)
flutter_ios_podfile_setup

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

# ✅ 하나만 남겨두세요
post_install do |installer|
  installer.pods_project.targets.each do |t|
    flutter_additional_ios_build_settings(t)
    t.build_configurations.each do |c|
      c.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end